-- MySQL Script generated by MySQL Workbench
-- Mon Feb  8 23:20:36 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema roadwiki
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema roadwiki
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `roadwiki` DEFAULT CHARACTER SET utf8 ;
USE `roadwiki` ;

-- -----------------------------------------------------
-- Table `roadwiki`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `roadwiki`.`user` (
  `uid` INT NOT NULL AUTO_INCREMENT,
  `password` VARCHAR(30) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `name` VARCHAR(30) NOT NULL,
  `createDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `image` VARCHAR(50) NULL,
  PRIMARY KEY (`uid`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) ,
  UNIQUE INDEX `uid_UNIQUE` (`uid` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `roadwiki`.`keyword`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `roadwiki`.`keyword` (
  `kwid` INT NOT NULL AUTO_INCREMENT,
  `word` VARCHAR(45) NULL,
  PRIMARY KEY (`kwid`),
  UNIQUE INDEX `kwid_UNIQUE` (`kwid` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `roadwiki`.`userkeyword`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `roadwiki`.`userkeyword` (
  `uid` INT NOT NULL,
  `priority` INT NULL,
  `kwid` INT NOT NULL,
  PRIMARY KEY (`uid`, `kwid`),
  INDEX `kwid_idx` (`kwid` ASC) ,
  CONSTRAINT `fk_user_userkeyword`
    FOREIGN KEY (`uid`)
    REFERENCES `roadwiki`.`user` (`uid`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_keyword_userkeyword`
    FOREIGN KEY (`kwid`)
    REFERENCES `roadwiki`.`keyword` (`kwid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `roadwiki`.`posting`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `roadwiki`.`posting` (
  `pid` INT NOT NULL AUTO_INCREMENT,
  `uid` INT NOT NULL,
  `classifier` VARCHAR(45) NOT NULL,
  `tag` VARCHAR(20) NULL,
  `title` VARCHAR(30) NOT NULL,
  `content` TEXT NOT NULL,
  `createDate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `modifyDate` TIMESTAMP NULL,
  `likeCnt` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`pid`),
  UNIQUE INDEX `pid_UNIQUE` (`pid` ASC) ,
  INDEX `uid_idx` (`uid` ASC) ,
  CONSTRAINT `fk_user_posting`
    FOREIGN KEY (`uid`)
    REFERENCES `roadwiki`.`user` (`uid`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `roadwiki`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `roadwiki`.`comment` (
  `cid` INT NOT NULL AUTO_INCREMENT,
  `uid` INT NOT NULL,
  `pid` INT NOT NULL,
  `content` TEXT NOT NULL,
  `createDate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `modifyDate` TIMESTAMP NULL,
  `likeCnt` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`cid`),
  UNIQUE INDEX `cid_UNIQUE` (`cid` ASC) ,
  INDEX `uid_idx` (`uid` ASC) ,
  INDEX `parentid_idx` (`pid` ASC) ,
  CONSTRAINT `fk_user_comment`
    FOREIGN KEY (`uid`)
    REFERENCES `roadwiki`.`user` (`uid`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_posting_comment`
    FOREIGN KEY (`pid`)
    REFERENCES `roadwiki`.`posting` (`pid`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `roadwiki`.`postinglikeuser`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `roadwiki`.`postinglikeuser` (
  `uid` INT NOT NULL,
  `pid` INT NOT NULL,
  PRIMARY KEY (`pid`, `uid`),
  INDEX `pid_idx` (`pid` ASC) ,
  CONSTRAINT `fk_posting_postinglikeuser`
    FOREIGN KEY (`pid`)
    REFERENCES `roadwiki`.`posting` (`pid`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_postinglikeuser`
    FOREIGN KEY (`uid`)
    REFERENCES `roadwiki`.`user` (`uid`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `roadwiki`.`commentlikeuser`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `roadwiki`.`commentlikeuser` (
  `uid` INT NOT NULL,
  `cid` INT NOT NULL,
  PRIMARY KEY (`cid`, `uid`),
  INDEX `cid_idx` (`cid` ASC) ,
  CONSTRAINT `fk_user_commentlikeuser`
    FOREIGN KEY (`uid`)
    REFERENCES `roadwiki`.`user` (`uid`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comment_commentlikeuser`
    FOREIGN KEY (`cid`)
    REFERENCES `roadwiki`.`comment` (`cid`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `roadwiki`.`roadmap`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `roadwiki`.`roadmap` (
  `rmid` INT NOT NULL AUTO_INCREMENT,
  `uid` INT NOT NULL,
  `name` VARCHAR(30) NULL,
  `rmorder` INT NULL,
  `permission` INT NULL DEFAULT 1,
  `createDate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `tmp` TEXT NULL,
  UNIQUE INDEX `rid_UNIQUE` (`rmid` ASC) ,
  INDEX `uid_idx` (`uid` ASC) ,
  PRIMARY KEY (`rmid`),
  CONSTRAINT `fk_user_roadmap`
    FOREIGN KEY (`uid`)
    REFERENCES `roadwiki`.`user` (`uid`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `roadwiki`.`recomment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `roadwiki`.`recomment` (
  `rcid` INT NOT NULL AUTO_INCREMENT,
  `uid` INT NOT NULL,
  `cid` INT NOT NULL,
  `content` TEXT NOT NULL,
  `createDate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `modifyDate` TIMESTAMP NULL,
  `likeCnt` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`rcid`),
  UNIQUE INDEX `rcid_UNIQUE` (`rcid` ASC) ,
  INDEX `fk_comment_recomment_idx` (`cid` ASC) ,
  INDEX `fk_user_recomment_idx` (`uid` ASC) ,
  CONSTRAINT `fk_comment_recomment`
    FOREIGN KEY (`cid`)
    REFERENCES `roadwiki`.`comment` (`cid`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_recomment`
    FOREIGN KEY (`uid`)
    REFERENCES `roadwiki`.`user` (`uid`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `roadwiki`.`recommentlikeuser`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `roadwiki`.`recommentlikeuser` (
  `uid` INT NOT NULL,
  `rcid` INT NOT NULL,
  PRIMARY KEY (`uid`, `rcid`),
  INDEX `fk_recomment_recommentlikeuser_idx` (`rcid` ASC) ,
  CONSTRAINT `fk_user_recommentlikeuser`
    FOREIGN KEY (`uid`)
    REFERENCES `roadwiki`.`user` (`uid`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_recomment_recommentlikeuser`
    FOREIGN KEY (`rcid`)
    REFERENCES `roadwiki`.`recomment` (`rcid`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `roadwiki`.`bigdata`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `roadwiki`.`bigdata` (
  `bdid` INT NOT NULL AUTO_INCREMENT,
  `text` VARCHAR(20) NULL,
  `content` TEXT NULL,
  PRIMARY KEY (`bdid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `roadwiki`.`middledata`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `roadwiki`.`middledata` (
  `mdid` INT NOT NULL AUTO_INCREMENT,
  `bdid` INT NOT NULL,
  `text` VARCHAR(20) NULL,
  `content` TEXT NULL,
  PRIMARY KEY (`mdid`, `bdid`),
  INDEX `fk_middledata_bigdata1_idx` (`bdid` ASC) ,
  CONSTRAINT `fk_bigdata_middledata`
    FOREIGN KEY (`bdid`)
    REFERENCES `roadwiki`.`bigdata` (`bdid`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `roadwiki`.`smalldata`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `roadwiki`.`smalldata` (
  `sdid` INT NOT NULL AUTO_INCREMENT,
  `mdid` INT NOT NULL,
  `bdid` INT NOT NULL,
  `text` VARCHAR(20) NULL,
  `content` TEXT NULL,
  PRIMARY KEY (`sdid`, `mdid`, `bdid`),
  INDEX `fk_smalldata_middledata1_idx` (`mdid` ASC, `bdid` ASC) ,
  CONSTRAINT `fk_middledata_smalldata`
    FOREIGN KEY (`mdid` , `bdid`)
    REFERENCES `roadwiki`.`middledata` (`mdid` , `bdid`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `roadwiki`.`small`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `roadwiki`.`small` (
  `key` INT NOT NULL,
  `rmid` INT NOT NULL,
  `sdid` INT NOT NULL,
  `loc` TEXT NULL,
  `memo` TEXT NULL,
  `startdate` TEXT NULL,
  `enddate` TEXT NULL,
  `category` TEXT NULL,
  INDEX `fk_small_smalldata1_idx` (`sdid` ASC) ,
  PRIMARY KEY (`rmid`, `key`),
  CONSTRAINT `fk_smalldata_small`
    FOREIGN KEY (`sdid`)
    REFERENCES `roadwiki`.`smalldata` (`sdid`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_roadmap_small`
    FOREIGN KEY (`rmid`)
    REFERENCES `roadwiki`.`roadmap` (`rmid`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `roadwiki`.`middle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `roadwiki`.`middle` (
  `key` INT NOT NULL,
  `rmid` INT NOT NULL,
  `mdid` INT NOT NULL,
  `loc` TEXT NULL,
  `memo` TEXT NULL,
  `startdate` TEXT NULL,
  `enddate` TEXT NULL,
  `category` TEXT NULL,
  INDEX `fk_middle_middledata1_idx` (`mdid` ASC) ,
  PRIMARY KEY (`rmid`, `key`),
  CONSTRAINT `fk_middledata_middle`
    FOREIGN KEY (`mdid`)
    REFERENCES `roadwiki`.`middledata` (`mdid`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_roadmap_middle`
    FOREIGN KEY (`rmid`)
    REFERENCES `roadwiki`.`roadmap` (`rmid`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `roadwiki`.`big`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `roadwiki`.`big` (
  `key` INT NOT NULL,
  `rmid` INT NOT NULL,
  `bdid` INT NOT NULL,
  `loc` TEXT NULL,
  `memo` TEXT NULL,
  `startdate` TEXT NULL,
  `enddate` TEXT NULL,
  `category` TEXT NULL,
  INDEX `fk_big_bigdata1_idx` (`bdid` ASC) ,
  PRIMARY KEY (`rmid`, `key`),
  CONSTRAINT `fk_bigdata_big`
    FOREIGN KEY (`bdid`)
    REFERENCES `roadwiki`.`bigdata` (`bdid`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_roadmap_big`
    FOREIGN KEY (`rmid`)
    REFERENCES `roadwiki`.`roadmap` (`rmid`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

use roadwiki;

insert into keyword 
values
(1, "Python"),
(2, "Java"),
(3, "C"),
(4, "Vue"),
(5, "Spring"),
(6, "Frontend"),
(7, "Backend"),
(8, "Database"),
(9, "AI"),
(10, "기타") ;


insert into user(email, password, name) values
('abc@abc.com','1234','김싸피'),
('abcd@abc.com','1234','김동화'),
('root@root.com','1234','김루트'),
("ssafy0@ssafy.com", "1234", "김하늘"),
("ssafy1@ssafy.com", "1234", "윤건상"),
("ssafy2@ssafy.com", "1234", "윤승환"),
("ssafy3@ssafy.com", "1234", "조명희"),
("ssafy4@ssafy.com", "1234", "김다민"),
("ssafy5@ssafy.com", "1234", "곽온겸");


update user set uid = -1 where uid = 3;